// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx4VX8WO2F19R4PBJV7KFMKMFKKAD6cSA',
    appId: '1:456400754992:web:9bc35e923909f5266690f5',
    messagingSenderId: '456400754992',
    projectId: 'abdi2004-notesapp',
    authDomain: 'abdi2004-notesapp.firebaseapp.com',
    storageBucket: 'abdi2004-notesapp.appspot.com',
    measurementId: 'G-RWKNHVY1Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHBBHkywVcXxojmK28wyem2vQNwRlfm3U',
    appId: '1:456400754992:android:6bd4eff6f707c99a6690f5',
    messagingSenderId: '456400754992',
    projectId: 'abdi2004-notesapp',
    storageBucket: 'abdi2004-notesapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgDNywL1s2m-Xdg5syeNXYZb79bsRIKc8',
    appId: '1:456400754992:ios:89054ce18eeef65c6690f5',
    messagingSenderId: '456400754992',
    projectId: 'abdi2004-notesapp',
    storageBucket: 'abdi2004-notesapp.appspot.com',
    iosBundleId: 'com.first.notetaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgDNywL1s2m-Xdg5syeNXYZb79bsRIKc8',
    appId: '1:456400754992:ios:89054ce18eeef65c6690f5',
    messagingSenderId: '456400754992',
    projectId: 'abdi2004-notesapp',
    storageBucket: 'abdi2004-notesapp.appspot.com',
    iosBundleId: 'com.first.notetaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx4VX8WO2F19R4PBJV7KFMKMFKKAD6cSA',
    appId: '1:456400754992:web:b309dc2ab0372b416690f5',
    messagingSenderId: '456400754992',
    projectId: 'abdi2004-notesapp',
    authDomain: 'abdi2004-notesapp.firebaseapp.com',
    storageBucket: 'abdi2004-notesapp.appspot.com',
    measurementId: 'G-P6B79B8MMM',
  );
}
